name: CI: Build blog.laolilin.com
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Update blog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repos
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install packages
      run: |
        bash scripts/00install_packages.sh
    - name: Install plugins
      run: |
        bash scripts/01install_plugins.sh
    - name: Install themes
      run: |
        bash scripts/02install_themes.sh
    - name: Execute build
      run: |
        bash scripts/51build_publish.sh
    - name: Push to repos
      run: |
        bash scripts/99done.sh
      env:
        PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}
